#!/bin/bash

echo "Visual alignment test:"
echo ""
echo "Raw characters (notice how emojis take more space):"
echo "['X']['✅']['ℹ️']['🚀']['ABC']"
echo ""
echo "With positioning markers:"
echo "0123456789012345678901234567890"
echo "X"
echo "✅"
echo "ℹ️"
echo "🚀"
echo "ABC"
echo ""
echo "Double test:"
echo "XX"
echo "✅✅"
echo "ℹ️ℹ️"
echo "🚀🚀"